### PR TITLE
Add web target to pkg builder in makefile

### PR DESCRIPTION
**Pull request by theref**
Aims to fix https://github.com/nucypher/nucypher-ts/issues/120

### CODE REVIEW

**Comment by piotr-roslaniec** [comment]
I assume this must be related to https://github.com/nucypher/nucypher-ts/issues/120

Does this technique fix the aforementioned issue? Did we test that locally?

**Comment by theref** [comment]
> I assume this must be related to [nucypher/nucypher-ts#120](https://github.com/nucypher/nucypher-ts/issues/120)
> 
> Does this technique fix the aforementioned issue? Did we test that locally?

yeah that's what I'm trying out now

**Comment by theref** [comment]
If you run `make pkg` in `nucypher-core-wasm` it will produce the required output in `nucypher-core-wasm/pkg/pkg-web`

I added a simple `test.html`:
```html
<html>
  <head>
    <script src="./nucypher_core_wasm.js"></script>
  </head>
  <body>
    <script>
      fetch("./nucypher_core_wasm_bg.wasm")
        .then(response => response.arrayBuffer())
        .then(buffer => WebAssembly.instantiate(buffer))
        .then(wasm => {
          const cond = Condition();
        });
    </script>
  </body>
</html>
```
This can then be opened with `python -m SimpleHTTPServer` (to avoid CORS nonsense). Unfortunately, I then get the error: `Uncaught SyntaxError: Unexpected token 'export' (at nucypher_core_wasm.js:219:1)`

I'm not really sure why the export is unexpected @piotr-roslaniec

**Comment by piotr-roslaniec** [comment]
@theref 
It probably means that the browser doesn't recognize the module structure of `nucypher_core_wasm.js` file.
We could try fixing it by adding a script `type` attribute:
```html
<script type="module" src="./nucypher_core_wasm.js"></script>
```
We can find confirmation for this workaround in [`wasm-pack` example for `--target web` compilation target](https://rustwasm.github.io/docs/wasm-bindgen/examples/without-a-bundler.html).

**Comment by theref** [comment]
@piotr-roslaniec Thank you, that link was really helpful and everything is working!

`test.html`:
```html
<html>
  <head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
  </head>
  <body>
    <script type="module">
      import init, { PublicKey } from './nucypher_core_wasm.js';

      async function run() {  
        await init();
        const pk = new PublicKey();
        console.log(pk);
      }
      run();
    </script>
  </body>
</html>
```

There is a bit of work to do to get the MIME types working correctly with the server. So create `wasm_server.py`:
```python
from http.server import HTTPServer, SimpleHTTPRequestHandler

class MyRequestHandler(SimpleHTTPRequestHandler):
    # Set the MIME type for .wasm files to application/wasm
    MIMETypes = {
        ".wasm": "application/wasm"
    }

# Start the HTTP server on port 8000
httpd = HTTPServer(('localhost', 8000), MyRequestHandler)
httpd.serve_forever()
```
And then `python3 wasm_server.py`, open `test.html` and in the console:
Screenshot 2022-12-15 at 11 53 01

**Comment by piotr-roslaniec** [comment]
@theref I'm glad to see that it works. Could we also get a confirmation that it simplifies `nucypher-ts` loading? I.e. re-use this setup to load newly packaged `nucypher-core` as a local dependency to `nucypher-ts` and try to load `nucypher-ts` into a webpage without WASM-aware bundler.

**Comment by piotr-roslaniec** [comment]
Rebased over https://github.com/nucypher/nucypher-core/pull/40

**Comment by fjarri** [comment]
Needs a few minor things:
- a changelog entry
- add the new directory to `package.template.json`

**Review by piotr-roslaniec — APPROVED** [review]
Let's get it in

**Comment by fjarri** [comment]
@theref, could you put the changes under `Unreleased` section in the changelog? Note that 0.5.0 has been released already, so perhaps rebase too.

**Comment by fjarri** [comment]
Disregard that, merged in #42

**Pull request closed without merging**
