### PR TITLE
Simplify serde support

### LINKED ISSUE #16: Support `serde` serialization to human-readable formats
Initially the objects in `nucypher-core` were only intended to be serialized in binary because we were only concerned with protocol objects. Recently an issue was raised on Discord about deserializing the JSON response from Porter with fields like 
```
      {
        "checksum_address": "314CaB1F5e6731f14F1deb4413d76b09D68710CA",
        "encrypting_key": "033c8e562e959b70714c96ec65cfd74f35d29526f8e8b38d148e8551b702dfb581"
      },
```

It would be convenient if these field could be deserialized by `serde` into `Address` and `PublicKey`. There are two problems here:
- `Address`'s `serde` serialization for human-readable formats is the `serde` default, that is a list of integers. So it cannot be deserialized from the hex form above at all. 
- While `PublicKey` would deserialize fine, it may be better to have a `0x` prefix in front of the hex representation, to match the Ethereum RPC format (and the same applies to `Address`). 

Naturally, fixing that should be done in a consistent manner. There are several interconnecting issues (which also affect `umbral`), so the scope of the changes needs to be determined.

Several bytearray-like objects in `nucypher-core` (`Address`, `FleetStateChecksum`, `HRAC` and the third-party `recoverable::Signature`) use the custom `arrays_as_bytes` serialization. `certificate_der` field of `NodeMetadataPayload` uses `serde_bytes`. These will have to be modified to support human-readable formats. One way to do it is to expose the machinery from `serde.rs` in `umbral` and use it in `nucypher-core`. The problem is that it deals with objects that are represented as arrays with size known at compile time, so that may have to be changed. 

`operator_signature` and `certificate_der` fields of `NodeMetadataPayload` may need to be wrapped in types so that we could impl `Serialize`/`Deserialize` for them. This way the `Option<recoverable::Signature>` that we need will be handled automatically, too. Now we need a special function in `arrays_as_bytes.rs` to handle it. 

Should we care about human-readable serialization of protocol objects? How will versioning work in this case?

### PR DESCRIPTION
**Pull request by fjarri**
Simplifies `serde` support, using the machinery for serialization with hex/base64 encoding from `umbral-pre`. This deprecates the custom `arrays_as_bytes.rs` (which did pretty much the same thing as the functions in `umbral-pre`) and the usage of `serde_bytes` crate (the functionality we needed from it is now covered by `umbral-pre`). Fixes #16 (because the `0x` prefixing is automatically inherited from `umbral-pre`).

Requires https://github.com/nucypher/rust-umbral/pull/94 to be built, so will have to wait until a new version of `umbral-pre` is released.

This PR technically changes ABI, but only for human-based formats, which we did not use previously anyway. The binary representation should stay the same. When choosing between hex/base64 for different objects, I used the same criteria as in `umbral-pre`: everything under 33 bytes is serialized as hex (`Address`, `HRAC`, `FleetStateChecksum`), the rest is `base64` (that includes the signatures).

### CODE REVIEW

**Comment by piotr-roslaniec** [comment]
@fjarri Should I look into fixing WASM bindings?

**Comment by fjarri** [comment]
> Should I look into fixing WASM bindings?

In what sense? These changes shouldn't affect the bindings.

**Comment by piotr-roslaniec** [comment]
> In what sense? These changes shouldn't affect the bindings.

I see. I saw that there are some `unresolved imports` errors and I assumed I should have my hand in it.

**Comment by fjarri** [comment]
Ah, it's just because it depends on the stuff in `umbral` that hasn't been published yet (https://github.com/nucypher/rust-umbral/pull/94).

**Review by theref — APPROVED** [review]

**Pull request merged**
