### PR TITLE
Indicate support for python 3.12

### PR DESCRIPTION
**Pull request by KPrasch**

### CODE REVIEW

**Review by piotr-roslaniec — APPROVED** [review]
Why do we need that? We should probably update `ferveo` too

**Comment by derekpierre** [comment]
Same question as @piotr-roslaniec - is there a reason to support 3.12 before launch? Either way `nucypher` only states that it supports up to python 3.11 at the moment.

If intended for like a 7.1.0 - we can create a 7.1.0 branch in `nucypher-core` if you like.

**Review by KPrasch — COMMENTED** [review]
`nucypher-core` is already compatible with python 3.12 without additional changes so this is more of a maintenance formality.  It will still be possible to use `nucypher-core-python` with python 3.8 if this PR is merged.  

That being said, there are noteworthy performance optimizations in python 3.12 that nodes can benefit from.  The largest consumers and primary audience of the nucypher/nucypher repo will launch nodes with docker, which we can ship against python 3.12 instead of 3.8.  By pre-building python wheels for 3.12 instead of 3.8 in this PR we optimize the newest version of python for the fastest install. 

Additionally, python 3.8 is around 10 months away from EOL (in fact active support ceased two years ago).

**Comment by KPrasch** [comment]
Also see https://github.com/nucypher/nucypher/pull/3327

**Comment by piotr-roslaniec** [comment]
Bumped Python version in `ferveo`: https://github.com/nucypher/ferveo/pull/166/commits/608cddc6f84bd1fcd652eb263515f21f61489c56

**Comment by piotr-roslaniec** [comment]
We should probably do the same for `umbral`?

**Comment by piotr-roslaniec** [comment]
Created https://github.com/nucypher/rust-umbral/pull/130

**Pull request merged**
